version: "3"

tasks:
  protoc-gen-go:
    aliases:
      - gen
    desc: "Генерирует код на go для gRPC"
    cmds:
      - protoc
        -I api/proto
        --go_out=./pkg/api
        --go_opt=paths=source_relative
        --go-grpc_out=./pkg/api
        --go-grpc_opt=paths=source_relative
        ./api/proto/*.proto
  migrate:
    desc: "
    Просматривает текущую активную версию миграции 
    и выполняет миграцию до конца
    (применяя все миграции вверх).
    "
    cmds:
      - ./migrator
        --storage-path ./storage/sso.db
        --migrations-path ./migrations
