version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc
        -I api/proto
        --go_out=./pkg/api
        --go_opt=paths=source_relative
        --go-grpc_out=./pkg/api
        --go-grpc_opt=paths=source_relative
        ./api/proto/*.proto
